apiVersion: v1
kind: Service
metadata:
  name: jobify-service
  labels:
    name: jobify-service
    app: jobify
spec:
  type: NodePort
  ports:
    - port: 5100
      targetPort: 5100
      nodePort: 30008
  selector:
    name: webapp-pod
    app: jobify
